print("Hola, queria saber cuanto esta el pijacomo")
print("-Buenas tardes, el pijacomo esta de oferta 2x1")
print("Genial! me llevo 4")
print("-En cuatro lo ponen señor")
print("Wow me atrapo bella dama")
print("-Tenemos promocion en culoacabo tambien")
print("Nunca oí de ese, que culoacabo?")
print("-Es nuetro producto estrella, esta 15% off")
print("Estupendo me llevo 4 pijacomo, y me llevo un culoacabo en mi compañero")
print("-Es nuestro cliente 100 del día, se ganó un té de anolamo")
print("Creo que es mi dia de suerte, voy  jugarle al permatrago")
print("-Que tenga una buen dia, Larry Capija")
print("Muchas garcias Debora Meltrozo")
